import { Unit, type PrismaClient } from "@prisma/client";

const normalizeForSearch = (str: string) =>
    str
        .normalize("NFD")
        .replace(/\p{Diacritic}/gu, "")
        .toLowerCase();

// Fiber values sourced from Ciqual (ANSES) and USDA FoodData Central.
// Piece weights are typical edible portions (peel included for fruits where applicable).
export const INGREDIENTS = [
    // ─── FRUITS ───────────────────────────────────────────────────────────────
    { id: "abricot", name: "Abricot", unit: Unit.PIECE, unitDisplay: null, fiberPerUnit: 1.0 },
    {
        id: "ananas-100g",
        name: "Ananas",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.4,
    },
    {
        id: "avocado-half",
        name: "Avocat (demi)",
        unit: Unit.PIECE,
        unitDisplay: "demi",
        fiberPerUnit: 5.0,
    },
    {
        id: "banana-small",
        name: "Banane petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.6,
    },
    {
        id: "banana-piece",
        name: "Banane moyenne",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 3.4,
    },
    {
        id: "banana-large",
        name: "Banane grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 4.2,
    },
    {
        id: "cerise-100g",
        name: "Cerises",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.6,
    },
    { id: "citron", name: "Citron", unit: Unit.PIECE, unitDisplay: null, fiberPerUnit: 1.5 },
    {
        id: "figue-fraiche",
        name: "Figue fraîche",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.5,
    },
    {
        id: "figue-sechee",
        name: "Figue séchée",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.5,
    },
    {
        id: "fraise-100g",
        name: "Fraises",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.0,
    },
    {
        id: "framboise-100g",
        name: "Framboises",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 6.5,
    },
    { id: "grenade", name: "Grenade", unit: Unit.PIECE, unitDisplay: null, fiberPerUnit: 4.0 },
    { id: "kiwi", name: "Kiwi", unit: Unit.PIECE, unitDisplay: null, fiberPerUnit: 2.2 },
    { id: "mandarine", name: "Mandarine", unit: Unit.PIECE, unitDisplay: null, fiberPerUnit: 1.4 },
    { id: "mangue", name: "Mangue", unit: Unit.PIECE, unitDisplay: null, fiberPerUnit: 3.2 },
    {
        id: "melon-tranche",
        name: "Melon (tranche)",
        unit: Unit.PIECE,
        unitDisplay: "tranche",
        fiberPerUnit: 1.8,
    },
    { id: "mure-100g", name: "Mûres", unit: Unit.HUNDRED_G, unitDisplay: null, fiberPerUnit: 5.3 },
    {
        id: "myrtille-100g",
        name: "Myrtilles",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.4,
    },
    {
        id: "orange-small",
        name: "Orange petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.9,
    },
    {
        id: "orange-medium",
        name: "Orange moyenne",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 3.9,
    },
    {
        id: "orange-large",
        name: "Orange grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 4.8,
    },
    {
        id: "pamplemousse-half",
        name: "Pamplemousse (demi)",
        unit: Unit.PIECE,
        unitDisplay: "demi",
        fiberPerUnit: 3.2,
    },
    {
        id: "peche-small",
        name: "Pêche petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.5,
    },
    {
        id: "peche-large",
        name: "Pêche grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.7,
    },
    {
        id: "pear-piece",
        name: "Poire petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 4.0,
    },
    {
        id: "pear-medium",
        name: "Poire moyenne",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 5.6,
    },
    {
        id: "pear-large",
        name: "Poire grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 7.4,
    },
    {
        id: "apple-small",
        name: "Pomme petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 3.1,
    },
    {
        id: "apple-piece",
        name: "Pomme moyenne",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 4.3,
    },
    {
        id: "apple-large",
        name: "Pomme grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 5.8,
    },
    { id: "prune", name: "Prune", unit: Unit.PIECE, unitDisplay: null, fiberPerUnit: 0.7 },
    {
        id: "pruneau-sec",
        name: "Pruneau séché",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 0.7,
    },
    {
        id: "raisin-100g",
        name: "Raisins frais",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 0.9,
    },

    // ─── LÉGUMES ──────────────────────────────────────────────────────────────
    {
        id: "artichaut",
        name: "Artichaut (cœur cuit)",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 5.5,
    },
    {
        id: "asperge-100g",
        name: "Asperges",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.1,
    },
    {
        id: "aubergine-small",
        name: "Aubergine petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 5.0,
    },
    {
        id: "aubergine-large",
        name: "Aubergine grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 10.0,
    },
    {
        id: "betterave-100g",
        name: "Betterave cuite",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.0,
    },
    {
        id: "broccoli-100g",
        name: "Brocoli",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.6,
    },
    {
        id: "carrot-small",
        name: "Carotte petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.4,
    },
    {
        id: "carrot-medium",
        name: "Carotte moyenne",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.2,
    },
    {
        id: "carrot-large",
        name: "Carotte grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 3.4,
    },
    {
        id: "celeri-branche",
        name: "Céleri branche",
        unit: Unit.PIECE,
        unitDisplay: "branche",
        fiberPerUnit: 0.6,
    },
    {
        id: "celeri-rave-100g",
        name: "Céleri-rave",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.8,
    },
    {
        id: "champignon-100g",
        name: "Champignons de Paris",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.0,
    },
    {
        id: "chou-blanc-100g",
        name: "Chou blanc",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.5,
    },
    {
        id: "chou-bruxelles-100g",
        name: "Choux de Bruxelles",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 3.8,
    },
    {
        id: "chou-fleur-100g",
        name: "Chou-fleur",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.0,
    },
    {
        id: "chou-kale-100g",
        name: "Chou kale",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 3.6,
    },
    {
        id: "concombre",
        name: "Concombre (petit)",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.0,
    },
    {
        id: "courgette-small",
        name: "Courgette petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.0,
    },
    {
        id: "courgette-large",
        name: "Courgette grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 3.5,
    },
    {
        id: "spinach-raw-100g",
        name: "Épinards",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.2,
    },
    {
        id: "fenouil",
        name: "Fenouil (bulbe)",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 6.2,
    },
    {
        id: "haricots-verts-100g",
        name: "Haricots verts",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 3.4,
    },
    {
        id: "mais-100g",
        name: "Maïs cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.4,
    },
    {
        id: "navet-moyen",
        name: "Navet moyen",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.7,
    },
    {
        id: "onion-small",
        name: "Oignon petit",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.2,
    },
    {
        id: "onion-medium",
        name: "Oignon moyen",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.9,
    },
    {
        id: "onion-large",
        name: "Oignon gros",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 3.0,
    },
    {
        id: "oignon-rouge-moyen",
        name: "Oignon rouge moyen",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.6,
    },
    {
        id: "panais-100g",
        name: "Panais",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 4.9,
    },
    {
        id: "sweet-potato-small",
        name: "Patate douce petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 3.0,
    },
    {
        id: "sweet-potato-medium",
        name: "Patate douce moyenne",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 5.3,
    },
    {
        id: "sweet-potato-large",
        name: "Patate douce grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 7.5,
    },
    {
        id: "petits-pois-100g",
        name: "Petits pois cuits",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 5.7,
    },
    {
        id: "leek-small",
        name: "Poireau petit",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.4,
    },
    {
        id: "leek-medium",
        name: "Poireau moyen",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.3,
    },
    {
        id: "leek-large",
        name: "Poireau gros",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 3.6,
    },
    {
        id: "poivron-rouge-moyen",
        name: "Poivron rouge moyen",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 3.2,
    },
    {
        id: "poivron-vert-moyen",
        name: "Poivron vert moyen",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.6,
    },
    {
        id: "potato-small",
        name: "Pomme de terre petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.8,
    },
    {
        id: "potato-medium",
        name: "Pomme de terre moyenne",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.7,
    },
    {
        id: "potato-large",
        name: "Pomme de terre grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 4.5,
    },
    {
        id: "roquette-100g",
        name: "Roquette",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.6,
    },
    {
        id: "salade-verte-100g",
        name: "Salade verte",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.3,
    },
    {
        id: "tomate-cerise-100g",
        name: "Tomates cerises",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.2,
    },
    {
        id: "tomate-small",
        name: "Tomate petite",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.0,
    },
    {
        id: "tomate-medium",
        name: "Tomate moyenne",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 1.5,
    },
    {
        id: "tomate-large",
        name: "Tomate grosse",
        unit: Unit.PIECE,
        unitDisplay: null,
        fiberPerUnit: 2.4,
    },
    {
        id: "topinambour-100g",
        name: "Topinambour",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.6,
    },

    // ─── FÉCULENTS (pour 100 g cuit) ─────────────────────────────────────────
    {
        id: "bulgur-100g",
        name: "Boulgour cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 4.5,
    },
    {
        id: "epeautre-100g",
        name: "Épeautre cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 3.8,
    },
    {
        id: "oats-100g",
        name: "Flocons d'avoine",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 10.1,
    },
    {
        id: "millet-100g",
        name: "Millet cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.3,
    },
    {
        id: "orge-perle-100g",
        name: "Orge perlé cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 3.8,
    },
    {
        id: "pasta-white-100g",
        name: "Pâtes blanches cuites",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.8,
    },
    {
        id: "pasta-whole-100g",
        name: "Pâtes complètes cuites",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 3.5,
    },
    {
        id: "quinoa-100g",
        name: "Quinoa cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.8,
    },
    {
        id: "white-rice-100g",
        name: "Riz blanc cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 0.4,
    },
    {
        id: "brown-rice-100g",
        name: "Riz complet cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.8,
    },
    {
        id: "wild-rice-100g",
        name: "Riz sauvage cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.8,
    },
    {
        id: "sarrasin-100g",
        name: "Sarrasin cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 2.7,
    },
    {
        id: "semoule-100g",
        name: "Semoule de blé cuite",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 1.4,
    },

    // ─── PAIN ─────────────────────────────────────────────────────────────────
    {
        id: "pain-blanc-tranche",
        name: "Pain blanc",
        unit: Unit.PIECE,
        unitDisplay: "tranche",
        fiberPerUnit: 0.8,
    },
    {
        id: "whole-wheat-bread-slice",
        name: "Pain complet",
        unit: Unit.PIECE,
        unitDisplay: "tranche",
        fiberPerUnit: 1.9,
    },
    {
        id: "pain-seigle-tranche",
        name: "Pain de seigle",
        unit: Unit.PIECE,
        unitDisplay: "tranche",
        fiberPerUnit: 1.9,
    },
    {
        id: "pain-cereales-tranche",
        name: "Pain aux céréales",
        unit: Unit.PIECE,
        unitDisplay: "tranche",
        fiberPerUnit: 1.3,
    },

    // ─── LÉGUMINEUSES (pour 100 g cuit) ──────────────────────────────────────
    {
        id: "edamame-100g",
        name: "Edamame cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 5.2,
    },
    {
        id: "feves-100g",
        name: "Fèves cuites",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 5.4,
    },
    {
        id: "haricots-blancs-100g",
        name: "Haricots blancs cuits",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 6.3,
    },
    {
        id: "black-beans-100g",
        name: "Haricots noirs cuits",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 8.7,
    },
    {
        id: "kidney-beans-100g",
        name: "Haricots rouges cuits",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 6.4,
    },
    {
        id: "lentils-beluga-100g",
        name: "Lentilles beluga cuites",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 7.5,
    },
    {
        id: "lentils-100g",
        name: "Lentilles vertes cuites",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 7.9,
    },
    {
        id: "lentils-red-100g",
        name: "Lentilles rouges cuites",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 5.5,
    },
    {
        id: "pois-casses-100g",
        name: "Pois cassés cuits",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 8.3,
    },
    {
        id: "chickpeas-100g",
        name: "Pois chiches cuits",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 7.6,
    },
    {
        id: "soja-100g",
        name: "Soja cuit",
        unit: Unit.HUNDRED_G,
        unitDisplay: null,
        fiberPerUnit: 6.0,
    },

    // ─── GRAINES & OLÉAGINEUX ─────────────────────────────────────────────────
    {
        id: "almonds-30g",
        name: "Amandes",
        unit: Unit.PIECE,
        unitDisplay: "poignée (30g)",
        fiberPerUnit: 3.5,
    },
    {
        id: "noisettes-30g",
        name: "Noisettes",
        unit: Unit.PIECE,
        unitDisplay: "poignée (30g)",
        fiberPerUnit: 2.7,
    },
    {
        id: "noix-30g",
        name: "Noix",
        unit: Unit.PIECE,
        unitDisplay: "poignée (30g)",
        fiberPerUnit: 2.0,
    },
    {
        id: "noix-cajou-30g",
        name: "Noix de cajou",
        unit: Unit.PIECE,
        unitDisplay: "poignée (30g)",
        fiberPerUnit: 0.9,
    },
    {
        id: "pistaches-30g",
        name: "Pistaches",
        unit: Unit.PIECE,
        unitDisplay: "poignée (30g)",
        fiberPerUnit: 3.0,
    },
    {
        id: "graines-chanvre-tbsp",
        name: "Graines de chanvre",
        unit: Unit.PIECE,
        unitDisplay: "c. à soupe",
        fiberPerUnit: 1.2,
    },
    {
        id: "chia-seeds-tbsp",
        name: "Graines de chia",
        unit: Unit.PIECE,
        unitDisplay: "c. à soupe",
        fiberPerUnit: 4.0,
    },
    {
        id: "graines-courge-30g",
        name: "Graines de courge",
        unit: Unit.PIECE,
        unitDisplay: "poignée (30g)",
        fiberPerUnit: 1.8,
    },
    {
        id: "flaxseeds-tbsp",
        name: "Graines de lin moulues",
        unit: Unit.PIECE,
        unitDisplay: "c. à soupe",
        fiberPerUnit: 1.9,
    },
    {
        id: "graines-pavot-tbsp",
        name: "Graines de pavot",
        unit: Unit.PIECE,
        unitDisplay: "c. à soupe",
        fiberPerUnit: 1.5,
    },
    {
        id: "graines-sesame-tbsp",
        name: "Graines de sésame",
        unit: Unit.PIECE,
        unitDisplay: "c. à soupe",
        fiberPerUnit: 0.9,
    },
    {
        id: "graines-tournesol-30g",
        name: "Graines de tournesol",
        unit: Unit.PIECE,
        unitDisplay: "poignée (30g)",
        fiberPerUnit: 2.7,
    },

    // ─── COMPLÉMENTS FIBRE ────────────────────────────────────────────────────
    { id: "garlic-clove", name: "Ail", unit: Unit.PIECE, unitDisplay: "gousse", fiberPerUnit: 0.1 },
    {
        id: "son-avoine-tbsp",
        name: "Son d'avoine",
        unit: Unit.PIECE,
        unitDisplay: "c. à soupe",
        fiberPerUnit: 1.8,
    },
    {
        id: "son-ble-tbsp",
        name: "Son de blé",
        unit: Unit.PIECE,
        unitDisplay: "c. à soupe",
        fiberPerUnit: 3.3,
    },
    {
        id: "wheat-germ-tbsp",
        name: "Germes de blé",
        unit: Unit.PIECE,
        unitDisplay: "c. à soupe",
        fiberPerUnit: 1.3,
    },
    {
        id: "brewer-yeast-tbsp",
        name: "Levure de bière",
        unit: Unit.PIECE,
        unitDisplay: "c. à soupe",
        fiberPerUnit: 0.5,
    },
    {
        id: "psyllium-tsp",
        name: "Psyllium",
        unit: Unit.PIECE,
        unitDisplay: "c. à café",
        fiberPerUnit: 3.5,
    },
];

export const seedIngredients = async (prisma: PrismaClient) => {
    for (const ingredient of INGREDIENTS) {
        const data = { ...ingredient, nameSearch: normalizeForSearch(ingredient.name) };
        await prisma.ingredient.upsert({
            where: { id: ingredient.id },
            update: data,
            create: data,
        });
    }
    console.log(`✓ ${INGREDIENTS.length} ingrédients seedés`);
};
