/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMealsRouteImport } from './routes/_app/meals'
import { Route as AppIngredientsRouteImport } from './routes/_app/ingredients'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBristolRouteImport } from './routes/_app/bristol'
import { Route as AppMealsIndexRouteImport } from './routes/_app/meals/index'
import { Route as AppMealsNewRouteImport } from './routes/_app/meals/new'
import { Route as AppMealsIdRouteImport } from './routes/_app/meals/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsRoute = AppMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppRoute,
} as any)
const AppIngredientsRoute = AppIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBristolRoute = AppBristolRouteImport.update({
  id: '/bristol',
  path: '/bristol',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsIndexRoute = AppMealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMealsRoute,
} as any)
const AppMealsNewRoute = AppMealsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppMealsRoute,
} as any)
const AppMealsIdRoute = AppMealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMealsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/bristol': typeof AppBristolRoute
  '/dashboard': typeof AppDashboardRoute
  '/ingredients': typeof AppIngredientsRoute
  '/meals': typeof AppMealsRouteWithChildren
  '/meals/$id': typeof AppMealsIdRoute
  '/meals/new': typeof AppMealsNewRoute
  '/meals/': typeof AppMealsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bristol': typeof AppBristolRoute
  '/dashboard': typeof AppDashboardRoute
  '/ingredients': typeof AppIngredientsRoute
  '/': typeof AppIndexRoute
  '/meals/$id': typeof AppMealsIdRoute
  '/meals/new': typeof AppMealsNewRoute
  '/meals': typeof AppMealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bristol': typeof AppBristolRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/ingredients': typeof AppIngredientsRoute
  '/_app/meals': typeof AppMealsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/meals/$id': typeof AppMealsIdRoute
  '/_app/meals/new': typeof AppMealsNewRoute
  '/_app/meals/': typeof AppMealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bristol'
    | '/dashboard'
    | '/ingredients'
    | '/meals'
    | '/meals/$id'
    | '/meals/new'
    | '/meals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bristol'
    | '/dashboard'
    | '/ingredients'
    | '/'
    | '/meals/$id'
    | '/meals/new'
    | '/meals'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/bristol'
    | '/_app/dashboard'
    | '/_app/ingredients'
    | '/_app/meals'
    | '/_app/'
    | '/_app/meals/$id'
    | '/_app/meals/new'
    | '/_app/meals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meals': {
      id: '/_app/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AppMealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingredients': {
      id: '/_app/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AppIngredientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bristol': {
      id: '/_app/bristol'
      path: '/bristol'
      fullPath: '/bristol'
      preLoaderRoute: typeof AppBristolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meals/': {
      id: '/_app/meals/'
      path: '/'
      fullPath: '/meals/'
      preLoaderRoute: typeof AppMealsIndexRouteImport
      parentRoute: typeof AppMealsRoute
    }
    '/_app/meals/new': {
      id: '/_app/meals/new'
      path: '/new'
      fullPath: '/meals/new'
      preLoaderRoute: typeof AppMealsNewRouteImport
      parentRoute: typeof AppMealsRoute
    }
    '/_app/meals/$id': {
      id: '/_app/meals/$id'
      path: '/$id'
      fullPath: '/meals/$id'
      preLoaderRoute: typeof AppMealsIdRouteImport
      parentRoute: typeof AppMealsRoute
    }
  }
}

interface AppMealsRouteChildren {
  AppMealsIdRoute: typeof AppMealsIdRoute
  AppMealsNewRoute: typeof AppMealsNewRoute
  AppMealsIndexRoute: typeof AppMealsIndexRoute
}

const AppMealsRouteChildren: AppMealsRouteChildren = {
  AppMealsIdRoute: AppMealsIdRoute,
  AppMealsNewRoute: AppMealsNewRoute,
  AppMealsIndexRoute: AppMealsIndexRoute,
}

const AppMealsRouteWithChildren = AppMealsRoute._addFileChildren(
  AppMealsRouteChildren,
)

interface AppRouteChildren {
  AppBristolRoute: typeof AppBristolRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIngredientsRoute: typeof AppIngredientsRoute
  AppMealsRoute: typeof AppMealsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBristolRoute: AppBristolRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIngredientsRoute: AppIngredientsRoute,
  AppMealsRoute: AppMealsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
