[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm turbo run build --filter=@fc/back"

[deploy]
startCommand = "pnpm --filter @fc/back start"
restartPolicyType = "on_failure"
