[build]
builder = "nixpacks"
buildCommand = "pnpm install --frozen-lockfile && pnpm --filter @fc/shared build && pnpm --filter @fc/back run build"

[deploy]
startCommand = "pnpm --filter @fc/back start"
restartPolicyType = "on_failure"
